/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Room_Set_010.glb --precision=10 --shadows 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room_Set_010.glb')
  return (
    <group position={[1.6,-2.15,-6]} scale={20} >
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.CF_BakedChroma_Walls.geometry} material={materials.Prod_Floor_Walls} />
        <mesh castShadow receiveShadow geometry={nodes.CF_BakedHigh_Chair.geometry} material={materials.Prod_High_Chair} position={[3.4829859734, 4.5523614883, 0.0489604473]} scale={1.3736045361} />
        <mesh castShadow receiveShadow geometry={nodes.CF_BakedpCube3.geometry} material={materials.Name_Board} position={[21.5216503143, -29.758972168, -22.4700622559]} scale={[1.3972266912, 0.1757114232, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.CF_BakedRound_Sofa2.geometry} material={materials.Blue_Sofa} />
        <mesh castShadow receiveShadow geometry={nodes.CF_BakedtypeMesh25.geometry} material={materials.Chroma_text} position={[21.4690914154, -29.3300228119, -25.8404712677]} />
        <mesh castShadow receiveShadow geometry={nodes.CF_BakedpolySurface106.geometry} material={materials.standardSurface12} />
        <mesh castShadow receiveShadow geometry={nodes.pCube3.geometry} material={materials.Name_boards} position={[21.5216503143, -29.758972168, -22.4700622559]} scale={[1.3972266912, 0.1757114232, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh007.geometry} material={materials.Sony_Camcorder} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh007_1.geometry} material={materials.Camera_Stand} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh009.geometry} material={materials.Sony_Camcorder} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh009_1.geometry} material={materials.Camera_Stand} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh006.geometry} material={materials.Hexa_table_Stand} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh006_1.geometry} material={materials.Chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh006_2.geometry} material={materials.Hexa_table_top} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh008.geometry} material={materials.Body} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh008_1.geometry} material={materials.Light} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.Desk.geometry} material={materials.PCR_Desk} />
        <mesh castShadow receiveShadow geometry={nodes.Glass_Partition.geometry} material={materials.Default_Material} position={[-40.5055923462, 12.163107872, -1.1229162216]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.HDD17.geometry} material={materials.PCR_HDD} position={[-18.7108230591, 135.0858612061, 0.0717496872]} rotation={[0, 0, -0.9701328862]} />
        <mesh castShadow receiveShadow geometry={nodes.HDD_Holder1.geometry} material={materials.PCR_HDD_Holder} />
        <mesh castShadow receiveShadow geometry={nodes.LIte_Putter.geometry} material={materials.PCR_lite_Putter} position={[-2.544718504, -9.0015621185, 1.3686249256]} rotation={[0, 0, -0.1284051773]} scale={[1.2537864447, 1.2537864447, 1.2537859678]} />
        <mesh castShadow receiveShadow geometry={nodes.Name_Board.geometry} material={materials.PCR_Name_Board} position={[17.0825653076, 15.2855119705, -22.4700660706]} scale={[1.3972266912, 0.1757114232, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.PCR1.geometry} material={materials.PCR_Name} position={[17.0300064087, 15.7144670486, -23.6392097473]} />
        <mesh castShadow receiveShadow geometry={nodes.PCR_PCR_Mac_Computer5.geometry} material={materials.PCR_Monitors} />
        <mesh castShadow receiveShadow geometry={nodes.PCR_Side_Monitor.geometry} material={materials.PCR_Wall_Monitors} position={[-6.7251868248, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Tannoy_Foam1.geometry} material={materials.PCR_Tannoy_Foam} />
        <mesh castShadow receiveShadow geometry={nodes.Tannoy_Speaker1.geometry} material={materials.PCR_Tannoy} position={[-0.0028403995, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Tricaster1.geometry} material={materials.PCR_Tricaster} position={[-37.1679573059, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Win_Keyboard.geometry} material={materials.PCR_Win_Keyboard} position={[10.8798789978, 20.6589756012, -4.2003669739]} rotation={[0.0793929201, -7.5e-9, 1.553463281]} scale={[0.6134922504, 0.6134922504, 0.6134921908]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.PCR_HDD_holder_Single.geometry} material={materials.PCR_HDD_Single} position={[8.9048576355, -0.8080673218, 1.1544713974]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.Audio_Equip_01.geometry} material={materials['Mac_keyboard.001']} position={[0, -1.4203872681, 0]} />
        <group position={[0, -1.4875488281, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh063.geometry} material={materials['Floor.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh063_1.geometry} material={materials.Audio_Room_Walls1} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh063_2.geometry} material={materials.lambert11} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh063_3.geometry} material={materials['PCR_Walls1.001']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Audio_Room_Keyboard1.geometry} material={materials.Audio_Room_Keyboard} />
        <mesh castShadow receiveShadow geometry={nodes.Audio_Room_Table1.geometry} material={materials.Audio_Room_Table} />
        <group position={[236.6046142578, -95.0088653564, -7.8829727173]} rotation={[-0.2124766398, 0, 0]} scale={[0.8222053647, 0.8222053051, 0.7804228663]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh067.geometry} material={materials['Monitor_Black1.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh067_1.geometry} material={materials.Audio_room_Monitor_border} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh067_2.geometry} material={materials.standardSurface2} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Glass_Partition1.geometry} material={materials.PCR_GLass} position={[200.7337341309, -89.9406585693, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.Name_Board3.geometry} material={materials['Name_boards.002']} position={[258.0744934082, -98.5874176025, -22.4700660706]} scale={[1.3972266912, 0.1757114232, 1]} />
        <group position={[238.6606445313, -113.4911422729, -2.9084396362]} rotation={[0, 0, -0.0091591993]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh057.geometry} material={materials['Mac_Screen.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh057_1.geometry} material={materials['Default_Material.003']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh057_2.geometry} material={materials['Mac_Mouse.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Apple_Logo001.geometry} material={materials['Mac_Screen.001']} position={[-36.5221366882, 8.8200511932, 2.8728101254]} rotation={[0, 0, 1.5672368697]} scale={[1.5782539845, 1.5782539845, 1.5782538652]} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Room_Name.geometry} material={materials['Room_Names.001']} position={[258.093170166, -98.0279388428, -28.9711017609]} />
        <mesh castShadow receiveShadow geometry={nodes.Sound_card1.geometry} material={materials.Volume} position={[0, -1.4875488281, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Speaker2.geometry} material={materials.AudioRoom_Speaker_Lft} position={[0, -1.4875488281, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Speaker_Holder_Pipe.geometry} material={materials.Sq_light} position={[0, -1.4875488281, 0]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <group position={[0, -6.5463409424, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh094.geometry} material={materials['Mac_Border.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh094_1.geometry} material={materials['Floor.003']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.AR_VR_Table.geometry} material={materials.Emerging_Tech_Table} position={[252.8950195313, -124.1845245361, 0.3659600914]} rotation={[0, 0, Math.PI / 2]} />
        <mesh castShadow receiveShadow geometry={nodes.Conputer.geometry} material={materials.Windows_Ketboard_mouse} position={[3.2349851131, -11.3169240952, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Door.geometry} material={materials.Emerging_Walls1} position={[462.9855041504, -181.7189483643, -6.4807872772]} />
        <mesh castShadow receiveShadow geometry={nodes.Emerging_Walls.geometry} material={materials.Emerging_Walls1} />
        <group position={[339.8065185547, -195.5663146973, 1.6714477539]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh096.geometry} material={materials['Monitor_Black1.002']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh096_1.geometry} material={materials.Monitor_LG_Border_Silver} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh096_2.geometry} material={materials.Monitor_LG__Border} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Quest3HMD.geometry} material={materials.Tricaster_White} position={[331.1095581055, -177.365447998, -5.3773460388]} rotation={[-0.3356192502, -0.1276603625, 0.3873235705]} scale={[0.0992502943, 0.0992502719, 0.0992502868]} />
        <group position={[0, -1.4133148193, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh088.geometry} material={materials['Resolve_Black_Balls.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh088_1.geometry} material={materials.Monitor_Black} />
        </group>
        <group position={[652.1879882813, -1.4133148193, 0]} rotation={[Math.PI, 0, 0]} scale={-1}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh095.geometry} material={materials['Resolve_Black_Balls.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh095_1.geometry} material={materials.Monitor_Black} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.VR_Mat.geometry} material={materials.VR_mat} position={[325.1252746582, -160.7595367432, -0.2917989492]} />
        <mesh castShadow receiveShadow geometry={nodes.Win_Keyboard1.geometry} material={materials.Win_Keyboard2} position={[318.6001586914, -177.4581451416, -4.2003669739]} rotation={[0.0793929201, -7.5e-9, 1.553463281]} scale={[0.6134922504, 0.6134922504, 0.6134921908]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <group position={[0, 0.5068626404, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.polySurface197.geometry} material={materials['PCR_Floor.001']} />
          <mesh castShadow receiveShadow geometry={nodes.polySurface198.geometry} material={materials['Material.001']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Mac_KeyBoard.geometry} material={materials['Mac_keyboard.002']} position={[-418.1159362793, 169.3990631104, 5.4128189087]} scale={1.7667822838} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.Door1.geometry} material={materials['lambert21.001']} position={[221.9125061035, -68.4691772461, -6.6812529564]} />
        <group position={[0, 5.7281603813, -1.7223193645]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh038.geometry} material={materials['Mac_Mouse.002']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh038_1.geometry} material={materials.Mac_Screen} />
        </group>
        <group position={[0, 5.7281646729, -1.7892409563]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh055.geometry} material={materials['HDD_Holder_White.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh055_1.geometry} material={materials.blinn13} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh055_2.geometry} material={materials.blinn10} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh055_3.geometry} material={materials.lambert23} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh055_4.geometry} material={materials.blinn12} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Edit_Room_Table_01001.geometry} material={materials['Emerging_Tech_Table.001']} />
        <mesh castShadow receiveShadow geometry={nodes.HDD15.geometry} material={materials['HDD_Sides.001']} position={[86.9911499023, -59.0896949768, -6.8623213768]} />
        <mesh castShadow receiveShadow geometry={nodes.HDD_Table_02.geometry} material={materials['HDD_Sides.001']} position={[133.2381744385, 60.0844078064, -1.722319603]} rotation={[0, 0, -0.9701328862]} />
        <mesh castShadow receiveShadow geometry={nodes.Mac_KeyBoards.geometry} material={materials['Mac_keyboard.003']} position={[0, 5.7281603813, -1.7223193645]}>
          <group position={[0, 0, 1.7223193645]}>
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But.geometry} material={materials['Mac_keyboard.003']} position={[197.3921051025, -63.1388130188, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But1.geometry} material={materials['Mac_keyboard.003']} position={[197.7014007568, -63.1388130188, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But10.geometry} material={materials['Mac_keyboard.003']} position={[200.1571655273, -63.1516036987, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But11.geometry} material={materials['Mac_keyboard.003']} position={[199.8499450684, -63.1511688232, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But12.geometry} material={materials['Mac_keyboard.003']} position={[201.0890655518, -63.1583938599, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But13.geometry} material={materials['Mac_keyboard.003']} position={[196.9273834229, -63.1388130188, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But2.geometry} material={materials['Mac_keyboard.003']} position={[198.3128356934, -63.1443862915, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But3.geometry} material={materials['Mac_keyboard.003']} position={[198.0062866211, -63.1388130188, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But4.geometry} material={materials['Mac_keyboard.003']} position={[198.6212005615, -63.1471633911, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But5.geometry} material={materials['Mac_keyboard.003']} position={[198.9284210205, -63.1443862915, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But6.geometry} material={materials['Mac_keyboard.003']} position={[199.2342529297, -63.1457748413, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But7.geometry} material={materials['Mac_keyboard.003']} position={[199.5442657471, -63.1511688232, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But8.geometry} material={materials['Mac_keyboard.003']} position={[200.7802429199, -63.1543807983, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
            <mesh castShadow receiveShadow geometry={nodes.Mac_Keyboard_But9.geometry} material={materials['Mac_keyboard.003']} position={[200.465423584, -63.1537971497, -6.7095332146]} rotation={[0.0619692257, 0, 0]} scale={0.223586306} />
          </group>
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Manequin_Stand.geometry} material={materials['Chrome.003']} position={[192.1390228271, -59.7946815491, -7.8602380753]} />
        <mesh castShadow receiveShadow geometry={nodes.Maniquin.geometry} material={materials['Manequin1.001']} position={[191.9817962646, -59.7823371887, -7.9369149208]} scale={1.1393951178} />
        <mesh castShadow receiveShadow geometry={nodes.Name_Board1.geometry} material={materials['Name_boards.003']} position={[110.6243972778, -68.4268798828, -23.0401744843]} scale={[1.3972266912, 0.1757114232, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.PCR2.geometry} material={materials['Room_Names.002']} position={[110.4902496338, -67.9337844849, -26.1773738861]} />
        <mesh castShadow receiveShadow geometry={nodes.PCR3.geometry} material={materials['Room_Names.002']} position={[110.4902496338, -67.9337844849, -13.8319702148]} />
        <group position={[183.2356719971, -58.9329605103, -2.6437356472]} rotation={[0.188974589, 0, 0]} scale={0.3107371032}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh028.geometry} material={materials.Resolve_Black1} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh028_1.geometry} material={materials.Monitor_Black1} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh028_2.geometry} material={materials.Resolve_Base} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh028_3.geometry} material={materials.Resolve_Console_Balls} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Tannoy_Foam.geometry} material={materials['PCR_Speaker_Tannoy.001']} position={[85.3820953369, -75.8319320679, -1.7566502094]} />
        <mesh castShadow receiveShadow geometry={nodes.Tannoy_Speaker.geometry} material={materials['Tannoy.001']} position={[85.3820953369, -75.8319320679, -1.7566496134]} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh035.geometry} material={materials['Floor.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh035_1.geometry} material={materials['Edit_Blue_Wall.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh035_2.geometry} material={materials['Audio_Room_Walls1.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <group position={[240.9934234619, -112.467338562, 0]}>
          <group position={[0, 0.1830749512, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh111.geometry} material={materials['Floor.005']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh111_1.geometry} material={materials['Prod_Floor_Walls.002']} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes.polySurface190001.geometry} material={materials['Material.002']} position={[0, -0.0000076294, 0]} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Base2001.geometry} material={materials['blinn28.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Edit_Floor1.geometry} material={materials['Edit_Blue_Wall.002']} position={[96.7755279541, -73.4729614258, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Guitar_Stand.geometry} material={materials['Drum_Set.001']} position={[263.8839111328, -130.4298706055, -1.1711398363]} />
        <mesh castShadow receiveShadow geometry={nodes.Wooden_Diffuser1.geometry} material={materials['Noise_Cancellation_block.001']} position={[-94.2468261719, 62.6653137207, 4.5601081848]} scale={1.4419271946} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh114.geometry} material={materials['Drum_Set.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh114_1.geometry} material={materials['Chrome.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh105.geometry} material={materials['Hartke.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh105_1.geometry} material={materials['Guitar_Box.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh104.geometry} material={materials['Diamond_Table_Stand.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh104_1.geometry} material={materials['Tri_Table_Top.001']} />
      </group>
      <group position={[-0.4107206166, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.Guitar_Stand001.geometry} material={materials['Drum_Set.002']} position={[261.3246765137, -93.5981903076, -1.1711370945]} />
      </group>
      <group position={[0.4894609153, 0, 0.6340928674]} rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.Door1001.geometry} material={materials['lambert21.002']} position={[28.9030303955, -93.0829162598, -6.4498605728]} scale={[1, 1, 0.9601076841]} />
      </group>
      <group position={[1.0380858183, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998}>
        <mesh castShadow receiveShadow geometry={nodes.Door1002.geometry} material={materials['lambert21.004']} position={[214.7968902588, -142.6922454834, -6.5320544243]} scale={[1.0355602503, 1, 1.00677526]} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Ceiling.geometry} material={materials.Ceiling} position={[0.2094780654, 0.3218306601, -0.0896997601]} rotation={[Math.PI / 2, 0, 0]} scale={0.0099999998} />
      <group position={[253.8002166748, 91.2846832275, 4.3964753151]} rotation={[0, 0, -0.7018416693]} scale={[1.7220535278, 1.7220535278, 1.7220531702]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh102.geometry} material={materials['Chair_Cloth.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh102_1.geometry} material={materials['Chair_Black.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh102_2.geometry} material={materials['Chair_Chrome1.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[4.2352385521, 0.0061709881, -1.6336938143]} rotation={[-Math.PI, 1.51e-7, -Math.PI]} scale={[-0.0235954039, -0.0034630653, -0.0235954039]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials['Material.004']} position={[4.2776112556, 0.0061709881, -1.6883220673]} rotation={[-Math.PI, 1.51e-7, -Math.PI]} scale={[-0.0235954039, -0.0034630653, -0.0235954039]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials['Material.005']} position={[4.3214464188, 0.0061709881, -1.6336938143]} rotation={[-Math.PI, 1.51e-7, -Math.PI]} scale={[-0.0235954039, -0.0034630653, -0.0235954039]} />
      <mesh castShadow receiveShadow geometry={nodes.AvatarEyelashes001.geometry} material={materials['AvatarEyelashes.001']} position={[4.2601370811, 0, -1.6445701122]} rotation={[-1.6410296451, -0.0017502855, -0.1320042703]} scale={[0.0691841915, 0.0691841841, 0.0691841841]} />
      <mesh castShadow receiveShadow geometry={nodes.AvatarEyelashes002.geometry} material={materials['AvatarEyelashes.002']} position={[4.4699788094, 0, -1.2981840372]} rotation={[-1.6298061109, 0, 0]} scale={[0.0966084301, 0.0966084376, 0.0966084376]} />
      <mesh castShadow receiveShadow geometry={nodes.AvatarLeftCornea002.geometry} material={materials['AvatarLeftCornea.002']} position={[4.3288311958, 0, -1.3629523516]} rotation={[-1.6298059374, 0, 0]} scale={[0.0626869351, 0.0626869276, 0.0626869276]} />
      <mesh castShadow receiveShadow geometry={nodes.AvatarLeftEyeball002.geometry} material={materials['AvatarLeftEyeball.002']} position={[4.4699788094, 0, -1.2981840372]} rotation={[-1.6298061109, 0, 0]} scale={[0.0966084301, 0.0966084376, 0.0966084376]} />
      <mesh castShadow receiveShadow geometry={nodes.AvatarRightCornea002.geometry} material={materials['AvatarRightCornea.002']} position={[4.3288311958, 0, -1.3629523516]} rotation={[-1.6298059374, 0, 0]} scale={[0.0626869351, 0.0626869276, 0.0626869276]} />
      <mesh castShadow receiveShadow geometry={nodes.AvatarRightEyeball002.geometry} material={materials['AvatarRightEyeball.002']} position={[4.4699788094, 0, -1.2981840372]} rotation={[-1.6298061109, 0, 0]} scale={[0.0966084301, 0.0966084376, 0.0966084376]} />
    </group>
  )
}

useGLTF.preload('/Room_Set_010.glb')
